name: mocktail
description: A Dart mock library which simplifies mocking with null safety support and no manual mocks or code generation.
version: 0.3.0
repository: https://github.com/felangel/mocktail
homepage: https://github.com/felangel/mocktail/tree/main/packages/mocktail

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  collection: ^1.16.0
  matcher: ^0.12.12
  test: ^1.21.4

dev_dependencies:
  meta: ^1.8.0
